name: Deploy .NET API to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: webapp-netapi-poc-1756280788
  AZURE_WEBAPP_PACKAGE_PATH: './src/WeatherApi'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WeatherApi.csproj --source https://api.nuget.org/v3/index.json
      
    - name: Build application
      run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WeatherApi.csproj --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WeatherApi.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish application
      run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WeatherApi.csproj --configuration Release --no-build --output ./publish
      
    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
